### ISSUE TITLE
Need sudo for 'lttng list --kernel'

### ISSUE THREAD

**Issue by stevenbell** [lttng/lttng-docs#18]
The "Trace the Linux Kernel" section needs to specify `sudo` for the commands

    lttng list --kernel
    lttng list --kernel --syscall

(Lines 644-645 in the doc source at the moment)

**Comment by alexmonthy** [comment]
You do not need `sudo` if your user is part of the group called "tracing". See http://lttng.org/docs/v2.9/#doc-tracing-the-linux-kernel .

To add your user to the tracing group, you can do:

    sudo addgroup tracing
    sudo usermod -a -G tracing <username>

then log out and log back in. This should give you access to kernel tracing.

**Comment by stevenbell** [comment]
Right, but the rest of the commands in that section specify `sudo`.  Do the rest of the commands require `sudo` even if your user is part of the 'tracing' group?

**Comment by alexmonthy** [comment]
All interactions (list, enable-event, start, stop, etc.) with kernel traces should work if the user is part of "tracing".

You're right that the whole section specifies `sudo` though. It may imply that sudo is required for those commands. Let's see what the doc maintainers think about that.

**Comment by eepp** [comment]
I assume that the user is not part of the tracing group in this documentation. Thus if a command line fails with bad permissions or with no available (root) session daemon without using `sudo`, it should start with `sudo`. That's just the style of this document. Being part of the tracing group is not mandatory, and there's a link to the tracing group details in a few places where `sudo` is used in the text.

So this issue is real. I'll fix it soon. @stevenbell I would also appreciate a PR for the two latest versions (currently v2.8 and v2.9) next time you find a mistake.

**Comment by eepp** [comment]
And especially for a quick start, I don't want to add those steps just to try the project. It's also not super trivial to be part of this new group without relogging, another hurdle to trying LTTng.
